version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: crypto_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: crypto_redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: crypto_api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/cryptotracker
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - API_SECURITY_TOKEN_SECRET=senha-super-secreta-nexwallet-123

volumes:
  mongo_data: